//Home
export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA';
export const GET_GLOBAL_DATA_SUCCESS = 'GET_GLOBAL_DATA_SUCCESS';
export const GET_GLOBAL_DATA_FAIL = 'GET_GLOBAL_DATA_FAIL';

//CountryInfo
export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
export const GET_COUNTRY_DATA_SUCCESS = 'GET_COUNTRY_DATA_SUCCESS';
export const GET_COUNTRY_DATA_FAIL = 'GET_COUNTRY_DATA_FAIL';
